[#62] refac error case
SpartaCoding-iOS5/LuckVii pull request #66
Opened 2024-12-18 14:07 UTC by jbnong07

Error case를 추가하고 guard 문에서 단순히 print문만 있거나 return 되는 부분
그리고 중복되는 리턴 처리를 수정했습니다.
추후 알럿 등과 같은 사용자친화적인 에러처리를 더하면 좋겠습니다.

2024-12-18 14:23 UTC, maxminseok approved these changes

2024-12-18 14:25 UTC, gyeomsony approved these changes
고생하셨숩니다~!

2024-12-18 22:28 UTC, jeff-0324 approved these changes
고생하셨습니다!

2024-12-18 23:50 UTC, name-mun requested changes
고생하셨습니다! `SelectDateVC` 충돌 나는 것만 해결하면 될 것 같아요 ~!

2024-12-18 23:50 UTC, name-mun commented on LuckVii/LuckVii/Controller/SelectDateViewController.swift
> +        do {
제가 이전 PR에서 해당 파일을 수정하고 병합해서 충돌이 있다고 나오네요..! `pull` 하고 충돌 해결해야 될 것 같아요!

2024-12-19 00:38 UTC, jbnong07 commented on LuckVii/LuckVii/Controller/SelectDateViewController.swift
> +        do {
제 거에 풀 땡기고 컨플릭트 나는 부분 체크해봤는데
제가 수정한 부분이 겹치네요
근데 제가 수정한 방향이 더 나은 쪽이라 제 거로 수정해야 하는데 지금 수정한 파일이 기존 파일과 다를 게 없는데 올리면 해결이 될까요?

2024-12-19 00:54 UTC, name-mun approved these changes
충돌 해결 되었네요! 고생하셨습니다~

2024-12-19 01:04 UTC, merged